/*
 * This source file was generated by the Gradle 'init' task
 */
package at.fhv.lka2.checker

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.fail

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
