/*
 * This source file was generated by the Gradle 'init' task
 */
package at.fhv.lka2.checker

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.nulls.shouldNotBeNull

class AppTest : FreeSpec({
    "app has a greeting" {
        val classUnderTest = App()
        classUnderTest.greeting.shouldNotBeNull()
    }
})
